"""Ordered, immutable Skill persistence migrations."""

from .v0001_initial import CURRENT_SCHEMA_VERSION, INITIAL_SCHEMA, SKILL_SCHEMA_NAMESPACE

SKILL_SCHEMA_MIGRATIONS = (INITIAL_SCHEMA,)

assert SKILL_SCHEMA_MIGRATIONS[-1].version == CURRENT_SCHEMA_VERSION

__all__ = [
    "CURRENT_SCHEMA_VERSION",
    "SKILL_SCHEMA_MIGRATIONS",
    "SKILL_SCHEMA_NAMESPACE",
]
