"""Standalone local Skill management API."""

from .bundle import compute_content_hash, deserialize_files, frontmatter_value, parse_version_label, serialize_files
from .context import ResolvedSkillContext, resolve_detected_contexts
from .installer import SkillInstaller
from .models import (
    DuplicateAction,
    ExportSkillRequest,
    ExportSkillResult,
    ManagedSkill,
    PendingSkillOperation,
    PendingSkillOperationStatus,
    PendingSkillOperationType,
    PublishSkillRequest,
    PublishSkillResult,
    PullResult,
    PushResult,
    RegisterSkillRequest,
    RegisterSkillResult,
    SkillDetail,
    SkillDiffResult,
    SkillManagementDetail,
    SkillManagementOverview,
    SkillManagementSummary,
    SkillManagementSyncState,
    SkillSnapshot,
    SnapshotFile,
    SnapshotFileRole,
    push_operation_id,
    trajectory_report_operation_id,
)
from .repository import SkillRepository
from .service import LocalSkillManager
from .snapshot import (
    read_skill_snapshot,
    snapshot_from_candidate,
    snapshot_from_cloud_bundle,
    snapshot_from_cloud_content,
    snapshot_from_editor,
    snapshot_from_editor_files,
    snapshot_from_record,
    snapshot_metadata,
    snapshot_with_runtime,
)

__all__ = [
    "DuplicateAction",
    "ExportSkillRequest",
    "ExportSkillResult",
    "LocalSkillManager",
    "ManagedSkill",
    "PendingSkillOperation",
    "PendingSkillOperationStatus",
    "PendingSkillOperationType",
    "PublishSkillRequest",
    "PublishSkillResult",
    "PullResult",
    "PushResult",
    "RegisterSkillRequest",
    "RegisterSkillResult",
    "ResolvedSkillContext",
    "SkillDetail",
    "SkillDiffResult",
    "SkillManagementDetail",
    "SkillManagementOverview",
    "SkillManagementSummary",
    "SkillManagementSyncState",
    "SkillInstaller",
    "SkillRepository",
    "SkillSnapshot",
    "SnapshotFile",
    "SnapshotFileRole",
    "compute_content_hash",
    "deserialize_files",
    "frontmatter_value",
    "parse_version_label",
    "read_skill_snapshot",
    "resolve_detected_contexts",
    "serialize_files",
    "snapshot_from_cloud_bundle",
    "snapshot_from_candidate",
    "snapshot_from_cloud_content",
    "snapshot_from_editor",
    "snapshot_from_editor_files",
    "snapshot_metadata",
    "snapshot_from_record",
    "snapshot_with_runtime",
    "push_operation_id",
    "trajectory_report_operation_id",
]
